[package]
name = "nlp_bot_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
sqlx = { version = "0.7.3", features = [ "runtime-tokio", "sqlite", "macros" ] }
tokio = { version = "1.35.0", features = ["macros", "rt-multi-thread"] }
